name: pubbie_cli
description: A sample command-line application.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.2 <3.0.0'

executables:
  pubbie: pubbie_cli

dependencies:
  shelf: ^1.4.1
  shelf_multipart: ^1.0.0
  shelf_router: ^1.1.4
  http: ^0.13.6
  args: ^2.4.1
  mason_logger: ^0.2.5
  universal_io: ^2.2.0

dev_dependencies:
  build_runner: ^2.3.3
  build_version: ^2.1.1
  lints: ^2.0.0
  test: ^1.21.0
