name: pubbie_cli
description: A sample command-line application.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.2 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.3
  build_version: ^2.1.1
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  args: ^2.4.1
  mason_logger: ^0.2.5
  universal_io: ^2.2.0
